name: pipe
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipe:
    uses: platform-mesh/.github/.github/workflows/pipeline-node-app.yml@f46cca01afbb79f80cd440cbdfd1538963c2ad24 # main
    secrets: inherit
    with:
      imageTagName: ghcr.io/platform-mesh/generic-resource-ui
      componentVersionKey: generic-resource-ui
