name: pipe
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipe:
    uses: platform-mesh/.github/.github/workflows/pipeline-node-app.yml@dd27a1f823d8216ff56657d0e234f8b5b9d5e66e # main
    secrets: inherit
    with:
      imageTagName: ghcr.io/platform-mesh/generic-resource-ui
      componentVersionKey: generic-resource-ui
